"""add_active_persona_to_users

Revision ID: 8ff1f9138cea
Revises: 
Create Date: 2025-12-07 19:33:07.676640+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # SQLModel desteği

from alembic import op

# Revision identifiers, used by Alembic.
revision: str = '8ff1f9138cea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Migration'ı uygula."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_persona', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False, server_default='standard'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Migration'ı geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('active_persona')

    # ### end Alembic commands ###

